# Generated by Django 4.2.7 on 2023-11-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Descriptions'),
        ),
    ]
